const data = [
    ["&plus;", "plus"],
    ["&minus;", "minus"],
    ["&times;", "times"],
    ["&div;", "divide"],
    ["&not;", "logical negation"],
    ["&and;", "logical and"],
    ["&or;", "logical and"],
    ["&forall;", "universal quantification"],
    ["&exist;", "existential quantification"],
    ["&Nopf;"],
    ["&Zopf;"],
    ["&Qopf;"],
    ["&Ropf;"],
    ["&Copf;"],
    ["&because;", "because"],
    ["&there4;", "therefore"],
    ["&sum;", "summation"],
    ["&prod;", "product"],
    ["&ee;", "napier's constant"],
    ["&ii;", "imaginary unit"],
    ["&pi;", "pi"],
    ["&rarr;", "right arrow"],
    ["&rArr;", "right arrow"],
    ["&Rarr;", "right arrow"],
    ["&larr;", "left arrow"],
    ["&lArr;", "left arrow"],
    ["&Larr;", "left arrow"],
];